services:

  my_db:
    container_name: my_db
    image: postgres:14.17-bookworm
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      retries: 5

  app:
    container_name: app
    build: .
    depends_on:
      - my_db
    env_file:
      - .env
    ports:
      - 8000:8000
